//
//This is the POC for metric-backend service that supports
//1. receiving usage reports from pipeline-backend and model-backend clients
//2. uploading usage to InfluxDB
//3. uploading usage to Stripe
//4. responding usage/price enquiries from clients

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/metric/v1beta/metric_service.proto

package metricv1beta

import (
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_metric_v1beta_metric_service_proto protoreflect.FileDescriptor

const file_core_metric_v1beta_metric_service_proto_rawDesc = "" +
	"\n" +
	"'core/metric/v1beta/metric_service.proto\x12\x12core.metric.v1beta\x1a\x1fcore/metric/v1beta/metric.proto\x1a\x1bgoogle/api/visibility.proto2\xc3\f\n" +
	"\x0fPipelineService\x12a\n" +
	"\fGetPipelines\x12'.core.metric.v1beta.GetPipelinesRequest\x1a(.core.metric.v1beta.GetPipelinesResponse\x12|\n" +
	"\x15ReportPipelineTrigger\x120.core.metric.v1beta.ReportPipelineTriggerRequest\x1a1.core.metric.v1beta.ReportPipelineTriggerResponse\x12\x7f\n" +
	"\x16ReportPipelineTriggers\x121.core.metric.v1beta.ReportPipelineTriggersRequest\x1a2.core.metric.v1beta.ReportPipelineTriggersResponse\x12\x88\x01\n" +
	"\x19GetPipelineTriggerRecords\x124.core.metric.v1beta.GetPipelineTriggerRecordsRequest\x1a5.core.metric.v1beta.GetPipelineTriggerRecordsResponse\x12\x94\x01\n" +
	"\x1dGetBulkPipelineTriggerRecords\x128.core.metric.v1beta.GetBulkPipelineTriggerRecordsRequest\x1a9.core.metric.v1beta.GetBulkPipelineTriggerRecordsResponse\x12\xa6\x01\n" +
	"#GetCumulativePipelineTriggerRecords\x12>.core.metric.v1beta.GetCumulativePipelineTriggerRecordsRequest\x1a?.core.metric.v1beta.GetCumulativePipelineTriggerRecordsResponse\x12\xb2\x01\n" +
	"'GetBulkCumulativePipelineTriggerRecords\x12B.core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsRequest\x1aC.core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsResponse\x12\x88\x01\n" +
	"\x19GetPipelineTriggerSummary\x124.core.metric.v1beta.GetPipelineTriggerSummaryRequest\x1a5.core.metric.v1beta.GetPipelineTriggerSummaryResponse\x12\x9a\x01\n" +
	"\x1fGetBulkPipelineTriggerSummaries\x12:.core.metric.v1beta.GetBulkPipelineTriggerSummariesRequest\x1a;.core.metric.v1beta.GetBulkPipelineTriggerSummariesResponse\x12\x82\x01\n" +
	"\x17GetPipelineTriggerPrice\x122.core.metric.v1beta.GetPipelineTriggerPriceRequest\x1a3.core.metric.v1beta.GetPipelineTriggerPriceResponse\x12\x8e\x01\n" +
	"\x1bGetBulkPipelineTriggerPrice\x126.core.metric.v1beta.GetBulkPipelineTriggerPriceRequest\x1a7.core.metric.v1beta.GetBulkPipelineTriggerPriceResponse\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL2\xb6\v\n" +
	"\fModelService\x12X\n" +
	"\tGetModels\x12$.core.metric.v1beta.GetModelsRequest\x1a%.core.metric.v1beta.GetModelsResponse\x12p\n" +
	"\x11ReportModelOnline\x12,.core.metric.v1beta.ReportModelOnlineRequest\x1a-.core.metric.v1beta.ReportModelOnlineResponse\x12s\n" +
	"\x12ReportModelOnlines\x12-.core.metric.v1beta.ReportModelOnlinesRequest\x1a..core.metric.v1beta.ReportModelOnlinesResponse\x12|\n" +
	"\x15GetModelOnlineRecords\x120.core.metric.v1beta.GetModelOnlineRecordsRequest\x1a1.core.metric.v1beta.GetModelOnlineRecordsResponse\x12\x88\x01\n" +
	"\x19GetBulkModelOnlineRecords\x124.core.metric.v1beta.GetBulkModelOnlineRecordsRequest\x1a5.core.metric.v1beta.GetBulkModelOnlineRecordsResponse\x12\x9a\x01\n" +
	"\x1fGetCumulativeModelOnlineRecords\x12:.core.metric.v1beta.GetCumulativeModelOnlineRecordsRequest\x1a;.core.metric.v1beta.GetCumulativeModelOnlineRecordsResponse\x12\xa6\x01\n" +
	"#GetBulkCumulativeModelOnlineRecords\x12>.core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsRequest\x1a?.core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsResponse\x12|\n" +
	"\x15GetModelOnlineSummary\x120.core.metric.v1beta.GetModelOnlineSummaryRequest\x1a1.core.metric.v1beta.GetModelOnlineSummaryResponse\x12\x88\x01\n" +
	"\x19GetBulkModelOnlineSummary\x124.core.metric.v1beta.GetBulkModelOnlineSummaryRequest\x1a5.core.metric.v1beta.GetBulkModelOnlineSummaryResponse\x12v\n" +
	"\x13GetModelOnlinePrice\x12..core.metric.v1beta.GetModelOnlinePriceRequest\x1a/.core.metric.v1beta.GetModelOnlinePriceResponse\x12\x82\x01\n" +
	"\x17GetBulkModelOnlinePrice\x122.core.metric.v1beta.GetBulkModelOnlinePriceRequest\x1a3.core.metric.v1beta.GetBulkModelOnlinePriceResponse\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALB\xd9\x01\n" +
	"\x16com.core.metric.v1betaB\x12MetricServiceProtoP\x01ZAgithub.com/instill-ai/protogen-go/core/metric/v1beta;metricv1beta\xa2\x02\x03CMX\xaa\x02\x12Core.Metric.V1beta\xca\x02\x12Core\\Metric\\V1beta\xe2\x02\x1eCore\\Metric\\V1beta\\GPBMetadata\xea\x02\x14Core::Metric::V1betab\x06proto3"

var file_core_metric_v1beta_metric_service_proto_goTypes = []any{
	(*GetPipelinesRequest)(nil),                             // 0: core.metric.v1beta.GetPipelinesRequest
	(*ReportPipelineTriggerRequest)(nil),                    // 1: core.metric.v1beta.ReportPipelineTriggerRequest
	(*ReportPipelineTriggersRequest)(nil),                   // 2: core.metric.v1beta.ReportPipelineTriggersRequest
	(*GetPipelineTriggerRecordsRequest)(nil),                // 3: core.metric.v1beta.GetPipelineTriggerRecordsRequest
	(*GetBulkPipelineTriggerRecordsRequest)(nil),            // 4: core.metric.v1beta.GetBulkPipelineTriggerRecordsRequest
	(*GetCumulativePipelineTriggerRecordsRequest)(nil),      // 5: core.metric.v1beta.GetCumulativePipelineTriggerRecordsRequest
	(*GetBulkCumulativePipelineTriggerRecordsRequest)(nil),  // 6: core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsRequest
	(*GetPipelineTriggerSummaryRequest)(nil),                // 7: core.metric.v1beta.GetPipelineTriggerSummaryRequest
	(*GetBulkPipelineTriggerSummariesRequest)(nil),          // 8: core.metric.v1beta.GetBulkPipelineTriggerSummariesRequest
	(*GetPipelineTriggerPriceRequest)(nil),                  // 9: core.metric.v1beta.GetPipelineTriggerPriceRequest
	(*GetBulkPipelineTriggerPriceRequest)(nil),              // 10: core.metric.v1beta.GetBulkPipelineTriggerPriceRequest
	(*GetModelsRequest)(nil),                                // 11: core.metric.v1beta.GetModelsRequest
	(*ReportModelOnlineRequest)(nil),                        // 12: core.metric.v1beta.ReportModelOnlineRequest
	(*ReportModelOnlinesRequest)(nil),                       // 13: core.metric.v1beta.ReportModelOnlinesRequest
	(*GetModelOnlineRecordsRequest)(nil),                    // 14: core.metric.v1beta.GetModelOnlineRecordsRequest
	(*GetBulkModelOnlineRecordsRequest)(nil),                // 15: core.metric.v1beta.GetBulkModelOnlineRecordsRequest
	(*GetCumulativeModelOnlineRecordsRequest)(nil),          // 16: core.metric.v1beta.GetCumulativeModelOnlineRecordsRequest
	(*GetBulkCumulativeModelOnlineRecordsRequest)(nil),      // 17: core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsRequest
	(*GetModelOnlineSummaryRequest)(nil),                    // 18: core.metric.v1beta.GetModelOnlineSummaryRequest
	(*GetBulkModelOnlineSummaryRequest)(nil),                // 19: core.metric.v1beta.GetBulkModelOnlineSummaryRequest
	(*GetModelOnlinePriceRequest)(nil),                      // 20: core.metric.v1beta.GetModelOnlinePriceRequest
	(*GetBulkModelOnlinePriceRequest)(nil),                  // 21: core.metric.v1beta.GetBulkModelOnlinePriceRequest
	(*GetPipelinesResponse)(nil),                            // 22: core.metric.v1beta.GetPipelinesResponse
	(*ReportPipelineTriggerResponse)(nil),                   // 23: core.metric.v1beta.ReportPipelineTriggerResponse
	(*ReportPipelineTriggersResponse)(nil),                  // 24: core.metric.v1beta.ReportPipelineTriggersResponse
	(*GetPipelineTriggerRecordsResponse)(nil),               // 25: core.metric.v1beta.GetPipelineTriggerRecordsResponse
	(*GetBulkPipelineTriggerRecordsResponse)(nil),           // 26: core.metric.v1beta.GetBulkPipelineTriggerRecordsResponse
	(*GetCumulativePipelineTriggerRecordsResponse)(nil),     // 27: core.metric.v1beta.GetCumulativePipelineTriggerRecordsResponse
	(*GetBulkCumulativePipelineTriggerRecordsResponse)(nil), // 28: core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsResponse
	(*GetPipelineTriggerSummaryResponse)(nil),               // 29: core.metric.v1beta.GetPipelineTriggerSummaryResponse
	(*GetBulkPipelineTriggerSummariesResponse)(nil),         // 30: core.metric.v1beta.GetBulkPipelineTriggerSummariesResponse
	(*GetPipelineTriggerPriceResponse)(nil),                 // 31: core.metric.v1beta.GetPipelineTriggerPriceResponse
	(*GetBulkPipelineTriggerPriceResponse)(nil),             // 32: core.metric.v1beta.GetBulkPipelineTriggerPriceResponse
	(*GetModelsResponse)(nil),                               // 33: core.metric.v1beta.GetModelsResponse
	(*ReportModelOnlineResponse)(nil),                       // 34: core.metric.v1beta.ReportModelOnlineResponse
	(*ReportModelOnlinesResponse)(nil),                      // 35: core.metric.v1beta.ReportModelOnlinesResponse
	(*GetModelOnlineRecordsResponse)(nil),                   // 36: core.metric.v1beta.GetModelOnlineRecordsResponse
	(*GetBulkModelOnlineRecordsResponse)(nil),               // 37: core.metric.v1beta.GetBulkModelOnlineRecordsResponse
	(*GetCumulativeModelOnlineRecordsResponse)(nil),         // 38: core.metric.v1beta.GetCumulativeModelOnlineRecordsResponse
	(*GetBulkCumulativeModelOnlineRecordsResponse)(nil),     // 39: core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsResponse
	(*GetModelOnlineSummaryResponse)(nil),                   // 40: core.metric.v1beta.GetModelOnlineSummaryResponse
	(*GetBulkModelOnlineSummaryResponse)(nil),               // 41: core.metric.v1beta.GetBulkModelOnlineSummaryResponse
	(*GetModelOnlinePriceResponse)(nil),                     // 42: core.metric.v1beta.GetModelOnlinePriceResponse
	(*GetBulkModelOnlinePriceResponse)(nil),                 // 43: core.metric.v1beta.GetBulkModelOnlinePriceResponse
}
var file_core_metric_v1beta_metric_service_proto_depIdxs = []int32{
	0,  // 0: core.metric.v1beta.PipelineService.GetPipelines:input_type -> core.metric.v1beta.GetPipelinesRequest
	1,  // 1: core.metric.v1beta.PipelineService.ReportPipelineTrigger:input_type -> core.metric.v1beta.ReportPipelineTriggerRequest
	2,  // 2: core.metric.v1beta.PipelineService.ReportPipelineTriggers:input_type -> core.metric.v1beta.ReportPipelineTriggersRequest
	3,  // 3: core.metric.v1beta.PipelineService.GetPipelineTriggerRecords:input_type -> core.metric.v1beta.GetPipelineTriggerRecordsRequest
	4,  // 4: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerRecords:input_type -> core.metric.v1beta.GetBulkPipelineTriggerRecordsRequest
	5,  // 5: core.metric.v1beta.PipelineService.GetCumulativePipelineTriggerRecords:input_type -> core.metric.v1beta.GetCumulativePipelineTriggerRecordsRequest
	6,  // 6: core.metric.v1beta.PipelineService.GetBulkCumulativePipelineTriggerRecords:input_type -> core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsRequest
	7,  // 7: core.metric.v1beta.PipelineService.GetPipelineTriggerSummary:input_type -> core.metric.v1beta.GetPipelineTriggerSummaryRequest
	8,  // 8: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerSummaries:input_type -> core.metric.v1beta.GetBulkPipelineTriggerSummariesRequest
	9,  // 9: core.metric.v1beta.PipelineService.GetPipelineTriggerPrice:input_type -> core.metric.v1beta.GetPipelineTriggerPriceRequest
	10, // 10: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerPrice:input_type -> core.metric.v1beta.GetBulkPipelineTriggerPriceRequest
	11, // 11: core.metric.v1beta.ModelService.GetModels:input_type -> core.metric.v1beta.GetModelsRequest
	12, // 12: core.metric.v1beta.ModelService.ReportModelOnline:input_type -> core.metric.v1beta.ReportModelOnlineRequest
	13, // 13: core.metric.v1beta.ModelService.ReportModelOnlines:input_type -> core.metric.v1beta.ReportModelOnlinesRequest
	14, // 14: core.metric.v1beta.ModelService.GetModelOnlineRecords:input_type -> core.metric.v1beta.GetModelOnlineRecordsRequest
	15, // 15: core.metric.v1beta.ModelService.GetBulkModelOnlineRecords:input_type -> core.metric.v1beta.GetBulkModelOnlineRecordsRequest
	16, // 16: core.metric.v1beta.ModelService.GetCumulativeModelOnlineRecords:input_type -> core.metric.v1beta.GetCumulativeModelOnlineRecordsRequest
	17, // 17: core.metric.v1beta.ModelService.GetBulkCumulativeModelOnlineRecords:input_type -> core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsRequest
	18, // 18: core.metric.v1beta.ModelService.GetModelOnlineSummary:input_type -> core.metric.v1beta.GetModelOnlineSummaryRequest
	19, // 19: core.metric.v1beta.ModelService.GetBulkModelOnlineSummary:input_type -> core.metric.v1beta.GetBulkModelOnlineSummaryRequest
	20, // 20: core.metric.v1beta.ModelService.GetModelOnlinePrice:input_type -> core.metric.v1beta.GetModelOnlinePriceRequest
	21, // 21: core.metric.v1beta.ModelService.GetBulkModelOnlinePrice:input_type -> core.metric.v1beta.GetBulkModelOnlinePriceRequest
	22, // 22: core.metric.v1beta.PipelineService.GetPipelines:output_type -> core.metric.v1beta.GetPipelinesResponse
	23, // 23: core.metric.v1beta.PipelineService.ReportPipelineTrigger:output_type -> core.metric.v1beta.ReportPipelineTriggerResponse
	24, // 24: core.metric.v1beta.PipelineService.ReportPipelineTriggers:output_type -> core.metric.v1beta.ReportPipelineTriggersResponse
	25, // 25: core.metric.v1beta.PipelineService.GetPipelineTriggerRecords:output_type -> core.metric.v1beta.GetPipelineTriggerRecordsResponse
	26, // 26: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerRecords:output_type -> core.metric.v1beta.GetBulkPipelineTriggerRecordsResponse
	27, // 27: core.metric.v1beta.PipelineService.GetCumulativePipelineTriggerRecords:output_type -> core.metric.v1beta.GetCumulativePipelineTriggerRecordsResponse
	28, // 28: core.metric.v1beta.PipelineService.GetBulkCumulativePipelineTriggerRecords:output_type -> core.metric.v1beta.GetBulkCumulativePipelineTriggerRecordsResponse
	29, // 29: core.metric.v1beta.PipelineService.GetPipelineTriggerSummary:output_type -> core.metric.v1beta.GetPipelineTriggerSummaryResponse
	30, // 30: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerSummaries:output_type -> core.metric.v1beta.GetBulkPipelineTriggerSummariesResponse
	31, // 31: core.metric.v1beta.PipelineService.GetPipelineTriggerPrice:output_type -> core.metric.v1beta.GetPipelineTriggerPriceResponse
	32, // 32: core.metric.v1beta.PipelineService.GetBulkPipelineTriggerPrice:output_type -> core.metric.v1beta.GetBulkPipelineTriggerPriceResponse
	33, // 33: core.metric.v1beta.ModelService.GetModels:output_type -> core.metric.v1beta.GetModelsResponse
	34, // 34: core.metric.v1beta.ModelService.ReportModelOnline:output_type -> core.metric.v1beta.ReportModelOnlineResponse
	35, // 35: core.metric.v1beta.ModelService.ReportModelOnlines:output_type -> core.metric.v1beta.ReportModelOnlinesResponse
	36, // 36: core.metric.v1beta.ModelService.GetModelOnlineRecords:output_type -> core.metric.v1beta.GetModelOnlineRecordsResponse
	37, // 37: core.metric.v1beta.ModelService.GetBulkModelOnlineRecords:output_type -> core.metric.v1beta.GetBulkModelOnlineRecordsResponse
	38, // 38: core.metric.v1beta.ModelService.GetCumulativeModelOnlineRecords:output_type -> core.metric.v1beta.GetCumulativeModelOnlineRecordsResponse
	39, // 39: core.metric.v1beta.ModelService.GetBulkCumulativeModelOnlineRecords:output_type -> core.metric.v1beta.GetBulkCumulativeModelOnlineRecordsResponse
	40, // 40: core.metric.v1beta.ModelService.GetModelOnlineSummary:output_type -> core.metric.v1beta.GetModelOnlineSummaryResponse
	41, // 41: core.metric.v1beta.ModelService.GetBulkModelOnlineSummary:output_type -> core.metric.v1beta.GetBulkModelOnlineSummaryResponse
	42, // 42: core.metric.v1beta.ModelService.GetModelOnlinePrice:output_type -> core.metric.v1beta.GetModelOnlinePriceResponse
	43, // 43: core.metric.v1beta.ModelService.GetBulkModelOnlinePrice:output_type -> core.metric.v1beta.GetBulkModelOnlinePriceResponse
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_core_metric_v1beta_metric_service_proto_init() }
func file_core_metric_v1beta_metric_service_proto_init() {
	if File_core_metric_v1beta_metric_service_proto != nil {
		return
	}
	file_core_metric_v1beta_metric_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_metric_v1beta_metric_service_proto_rawDesc), len(file_core_metric_v1beta_metric_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_core_metric_v1beta_metric_service_proto_goTypes,
		DependencyIndexes: file_core_metric_v1beta_metric_service_proto_depIdxs,
	}.Build()
	File_core_metric_v1beta_metric_service_proto = out.File
	file_core_metric_v1beta_metric_service_proto_goTypes = nil
	file_core_metric_v1beta_metric_service_proto_depIdxs = nil
}
