// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: artifact/artifact/v1alpha/system_profile.proto

package artifactv1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemProfile represents a system-wide configuration profile
type SystemProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile name (e.g., "default", "enterprise", "free")
	Profile string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// Complete system configuration as structured JSON
	Config *structpb.Struct `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Description of this profile
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Last update time
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProfile) Reset() {
	*x = SystemProfile{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProfile) ProtoMessage() {}

func (x *SystemProfile) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProfile.ProtoReflect.Descriptor instead.
func (*SystemProfile) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{0}
}

func (x *SystemProfile) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SystemProfile) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SystemProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SystemProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetSystemProfileAdminRequest (admin only)
type GetSystemProfileAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile name, defaults to "default" if not specified
	Profile       string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemProfileAdminRequest) Reset() {
	*x = GetSystemProfileAdminRequest{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemProfileAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemProfileAdminRequest) ProtoMessage() {}

func (x *GetSystemProfileAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemProfileAdminRequest.ProtoReflect.Descriptor instead.
func (*GetSystemProfileAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemProfileAdminRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// GetSystemProfileAdminResponse (admin only)
type GetSystemProfileAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested system profile
	SystemProfile *SystemProfile `protobuf:"bytes,1,opt,name=system_profile,json=systemProfile,proto3" json:"system_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemProfileAdminResponse) Reset() {
	*x = GetSystemProfileAdminResponse{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemProfileAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemProfileAdminResponse) ProtoMessage() {}

func (x *GetSystemProfileAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemProfileAdminResponse.ProtoReflect.Descriptor instead.
func (*GetSystemProfileAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetSystemProfileAdminResponse) GetSystemProfile() *SystemProfile {
	if x != nil {
		return x.SystemProfile
	}
	return nil
}

// UpdateSystemProfileAdminRequest (admin only)
type UpdateSystemProfileAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The system profile to update (for upsert: create if doesn't exist, update if exists)
	SystemProfile *SystemProfile `protobuf:"bytes,1,opt,name=system_profile,json=systemProfile,proto3" json:"system_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemProfileAdminRequest) Reset() {
	*x = UpdateSystemProfileAdminRequest{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemProfileAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemProfileAdminRequest) ProtoMessage() {}

func (x *UpdateSystemProfileAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemProfileAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateSystemProfileAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSystemProfileAdminRequest) GetSystemProfile() *SystemProfile {
	if x != nil {
		return x.SystemProfile
	}
	return nil
}

// UpdateSystemProfileAdminResponse (admin only)
type UpdateSystemProfileAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated system profile
	SystemProfile *SystemProfile `protobuf:"bytes,1,opt,name=system_profile,json=systemProfile,proto3" json:"system_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemProfileAdminResponse) Reset() {
	*x = UpdateSystemProfileAdminResponse{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemProfileAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemProfileAdminResponse) ProtoMessage() {}

func (x *UpdateSystemProfileAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemProfileAdminResponse.ProtoReflect.Descriptor instead.
func (*UpdateSystemProfileAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSystemProfileAdminResponse) GetSystemProfile() *SystemProfile {
	if x != nil {
		return x.SystemProfile
	}
	return nil
}

// ListSystemProfilesAdminRequest (admin only)
type ListSystemProfilesAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSystemProfilesAdminRequest) Reset() {
	*x = ListSystemProfilesAdminRequest{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemProfilesAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemProfilesAdminRequest) ProtoMessage() {}

func (x *ListSystemProfilesAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemProfilesAdminRequest.ProtoReflect.Descriptor instead.
func (*ListSystemProfilesAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{5}
}

// ListSystemProfilesAdminResponse (admin only)
type ListSystemProfilesAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all system profiles
	SystemProfiles []*SystemProfile `protobuf:"bytes,1,rep,name=system_profiles,json=systemProfiles,proto3" json:"system_profiles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSystemProfilesAdminResponse) Reset() {
	*x = ListSystemProfilesAdminResponse{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSystemProfilesAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemProfilesAdminResponse) ProtoMessage() {}

func (x *ListSystemProfilesAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemProfilesAdminResponse.ProtoReflect.Descriptor instead.
func (*ListSystemProfilesAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{6}
}

func (x *ListSystemProfilesAdminResponse) GetSystemProfiles() []*SystemProfile {
	if x != nil {
		return x.SystemProfiles
	}
	return nil
}

// DeleteSystemProfileAdminRequest (admin only)
type DeleteSystemProfileAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile name to delete (cannot delete "default" profile)
	Profile       string `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSystemProfileAdminRequest) Reset() {
	*x = DeleteSystemProfileAdminRequest{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSystemProfileAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSystemProfileAdminRequest) ProtoMessage() {}

func (x *DeleteSystemProfileAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSystemProfileAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteSystemProfileAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSystemProfileAdminRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// DeleteSystemProfileAdminResponse (admin only)
type DeleteSystemProfileAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSystemProfileAdminResponse) Reset() {
	*x = DeleteSystemProfileAdminResponse{}
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSystemProfileAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSystemProfileAdminResponse) ProtoMessage() {}

func (x *DeleteSystemProfileAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_artifact_v1alpha_system_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSystemProfileAdminResponse.ProtoReflect.Descriptor instead.
func (*DeleteSystemProfileAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSystemProfileAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSystemProfileAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_artifact_artifact_v1alpha_system_profile_proto protoreflect.FileDescriptor

const file_artifact_artifact_v1alpha_system_profile_proto_rawDesc = "" +
	"\n" +
	".artifact/artifact/v1alpha/system_profile.proto\x12\x19artifact.artifact.v1alpha\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\rSystemProfile\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"8\n" +
	"\x1cGetSystemProfileAdminRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"p\n" +
	"\x1dGetSystemProfileAdminResponse\x12O\n" +
	"\x0esystem_profile\x18\x01 \x01(\v2(.artifact.artifact.v1alpha.SystemProfileR\rsystemProfile\"r\n" +
	"\x1fUpdateSystemProfileAdminRequest\x12O\n" +
	"\x0esystem_profile\x18\x01 \x01(\v2(.artifact.artifact.v1alpha.SystemProfileR\rsystemProfile\"s\n" +
	" UpdateSystemProfileAdminResponse\x12O\n" +
	"\x0esystem_profile\x18\x01 \x01(\v2(.artifact.artifact.v1alpha.SystemProfileR\rsystemProfile\" \n" +
	"\x1eListSystemProfilesAdminRequest\"t\n" +
	"\x1fListSystemProfilesAdminResponse\x12Q\n" +
	"\x0fsystem_profiles\x18\x01 \x03(\v2(.artifact.artifact.v1alpha.SystemProfileR\x0esystemProfiles\";\n" +
	"\x1fDeleteSystemProfileAdminRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"V\n" +
	" DeleteSystemProfileAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x86\x02\n" +
	"\x1dcom.artifact.artifact.v1alphaB\x12SystemProfileProtoP\x01ZKgithub.com/instill-ai/protogen-go/artifact/artifact/v1alpha;artifactv1alpha\xa2\x02\x03AAX\xaa\x02\x19Artifact.Artifact.V1alpha\xca\x02\x19Artifact\\Artifact\\V1alpha\xe2\x02%Artifact\\Artifact\\V1alpha\\GPBMetadata\xea\x02\x1bArtifact::Artifact::V1alphab\x06proto3"

var (
	file_artifact_artifact_v1alpha_system_profile_proto_rawDescOnce sync.Once
	file_artifact_artifact_v1alpha_system_profile_proto_rawDescData []byte
)

func file_artifact_artifact_v1alpha_system_profile_proto_rawDescGZIP() []byte {
	file_artifact_artifact_v1alpha_system_profile_proto_rawDescOnce.Do(func() {
		file_artifact_artifact_v1alpha_system_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_artifact_v1alpha_system_profile_proto_rawDesc), len(file_artifact_artifact_v1alpha_system_profile_proto_rawDesc)))
	})
	return file_artifact_artifact_v1alpha_system_profile_proto_rawDescData
}

var file_artifact_artifact_v1alpha_system_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_artifact_artifact_v1alpha_system_profile_proto_goTypes = []any{
	(*SystemProfile)(nil),                    // 0: artifact.artifact.v1alpha.SystemProfile
	(*GetSystemProfileAdminRequest)(nil),     // 1: artifact.artifact.v1alpha.GetSystemProfileAdminRequest
	(*GetSystemProfileAdminResponse)(nil),    // 2: artifact.artifact.v1alpha.GetSystemProfileAdminResponse
	(*UpdateSystemProfileAdminRequest)(nil),  // 3: artifact.artifact.v1alpha.UpdateSystemProfileAdminRequest
	(*UpdateSystemProfileAdminResponse)(nil), // 4: artifact.artifact.v1alpha.UpdateSystemProfileAdminResponse
	(*ListSystemProfilesAdminRequest)(nil),   // 5: artifact.artifact.v1alpha.ListSystemProfilesAdminRequest
	(*ListSystemProfilesAdminResponse)(nil),  // 6: artifact.artifact.v1alpha.ListSystemProfilesAdminResponse
	(*DeleteSystemProfileAdminRequest)(nil),  // 7: artifact.artifact.v1alpha.DeleteSystemProfileAdminRequest
	(*DeleteSystemProfileAdminResponse)(nil), // 8: artifact.artifact.v1alpha.DeleteSystemProfileAdminResponse
	(*structpb.Struct)(nil),                  // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),            // 10: google.protobuf.Timestamp
}
var file_artifact_artifact_v1alpha_system_profile_proto_depIdxs = []int32{
	9,  // 0: artifact.artifact.v1alpha.SystemProfile.config:type_name -> google.protobuf.Struct
	10, // 1: artifact.artifact.v1alpha.SystemProfile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: artifact.artifact.v1alpha.GetSystemProfileAdminResponse.system_profile:type_name -> artifact.artifact.v1alpha.SystemProfile
	0,  // 3: artifact.artifact.v1alpha.UpdateSystemProfileAdminRequest.system_profile:type_name -> artifact.artifact.v1alpha.SystemProfile
	0,  // 4: artifact.artifact.v1alpha.UpdateSystemProfileAdminResponse.system_profile:type_name -> artifact.artifact.v1alpha.SystemProfile
	0,  // 5: artifact.artifact.v1alpha.ListSystemProfilesAdminResponse.system_profiles:type_name -> artifact.artifact.v1alpha.SystemProfile
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_artifact_artifact_v1alpha_system_profile_proto_init() }
func file_artifact_artifact_v1alpha_system_profile_proto_init() {
	if File_artifact_artifact_v1alpha_system_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_artifact_v1alpha_system_profile_proto_rawDesc), len(file_artifact_artifact_v1alpha_system_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_artifact_v1alpha_system_profile_proto_goTypes,
		DependencyIndexes: file_artifact_artifact_v1alpha_system_profile_proto_depIdxs,
		MessageInfos:      file_artifact_artifact_v1alpha_system_profile_proto_msgTypes,
	}.Build()
	File_artifact_artifact_v1alpha_system_profile_proto = out.File
	file_artifact_artifact_v1alpha_system_profile_proto_goTypes = nil
	file_artifact_artifact_v1alpha_system_profile_proto_depIdxs = nil
}
