// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: artifact/v1alpha/chunk.proto

package artifactv1alpha

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type describes the type of a chunk content.
type Chunk_Type int32

const (
	// Unspecified.
	Chunk_TYPE_UNSPECIFIED Chunk_Type = 0
	// Content.
	Chunk_TYPE_CONTENT Chunk_Type = 1
	// Summary.
	Chunk_TYPE_SUMMARY Chunk_Type = 2
	// Augmented.
	Chunk_TYPE_AUGMENTED Chunk_Type = 3
)

// Enum value maps for Chunk_Type.
var (
	Chunk_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CONTENT",
		2: "TYPE_SUMMARY",
		3: "TYPE_AUGMENTED",
	}
	Chunk_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CONTENT":     1,
		"TYPE_SUMMARY":     2,
		"TYPE_AUGMENTED":   3,
	}
)

func (x Chunk_Type) Enum() *Chunk_Type {
	p := new(Chunk_Type)
	*p = x
	return p
}

func (x Chunk_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chunk_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_v1alpha_chunk_proto_enumTypes[0].Descriptor()
}

func (Chunk_Type) Type() protoreflect.EnumType {
	return &file_artifact_v1alpha_chunk_proto_enumTypes[0]
}

func (x Chunk_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chunk_Type.Descriptor instead.
func (Chunk_Type) EnumDescriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{0, 0}
}

// The Chunk message represents a chunk of data in the artifact system.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: The resource name of the chunk.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}/chunks/{chunk}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Field 2: The chunk id (unique identifier).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// whether the chunk is retrievable
	Retrievable bool `protobuf:"varint,3,opt,name=retrievable,proto3" json:"retrievable,omitempty"`
	// tokens of the chunk
	Tokens uint32 `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// creation time of the chunk
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The resource name of the original file this chunk belongs to.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}`
	OriginalFile string `protobuf:"bytes,6,opt,name=original_file,json=originalFile,proto3" json:"original_file,omitempty"`
	// chunk type
	Type Chunk_Type `protobuf:"varint,7,opt,name=type,proto3,enum=artifact.v1alpha.Chunk_Type" json:"type,omitempty"`
	// Reference to the position of the chunk within the original file.
	Reference *Chunk_Reference `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"`
	// Reference to the position of the chunk within the Markdown (source) file.
	MarkdownReference *Chunk_Reference `protobuf:"bytes,9,opt,name=markdown_reference,json=markdownReference,proto3" json:"markdown_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetRetrievable() bool {
	if x != nil {
		return x.Retrievable
	}
	return false
}

func (x *Chunk) GetTokens() uint32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *Chunk) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Chunk) GetOriginalFile() string {
	if x != nil {
		return x.OriginalFile
	}
	return ""
}

func (x *Chunk) GetType() Chunk_Type {
	if x != nil {
		return x.Type
	}
	return Chunk_TYPE_UNSPECIFIED
}

func (x *Chunk) GetReference() *Chunk_Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Chunk) GetMarkdownReference() *Chunk_Reference {
	if x != nil {
		return x.MarkdownReference
	}
	return nil
}

// ListChunksRequest represents a request to list chunks in the artifact system.
// Follows AIP-132: https://google.aip.dev/132
type ListChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of chunks to return. If this parameter is unspecified,
	// at most 100 chunks will be returned. The cap value for this parameter
	// is 1000 (i.e. any value above that will be coerced to 1000).
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Page token.
	PageToken *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Filter can hold an [AIP-160](https://google.aip.dev/160)-compliant filter
	// expression.
	// - `id="<uuid>"` or `uid="<uuid>"` - Filter by specific chunk ID/UID
	// - `chunk_type="CHUNK_TYPE_TEXT"` - Filter by chunk type
	// - `retrievable=true` - Filter by retrievable status
	//
	// **Examples**:
	// - List specific chunks: `id="uuid1" OR id="uuid2"`
	// - List text chunks: `chunk_type="CHUNK_TYPE_TEXT"`
	// - List retrievable chunks: `retrievable=true`
	Filter        *string `protobuf:"bytes,4,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksRequest) Reset() {
	*x = ListChunksRequest{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksRequest) ProtoMessage() {}

func (x *ListChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksRequest.ProtoReflect.Descriptor instead.
func (*ListChunksRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *ListChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListChunksRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListChunksRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListChunksRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

// ListChunksResponse represents a response containing a list of chunks in the
// artifact system.
type ListChunksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated chunks
	Chunks        []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksResponse) Reset() {
	*x = ListChunksResponse{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksResponse) ProtoMessage() {}

func (x *ListChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksResponse.ProtoReflect.Descriptor instead.
func (*ListChunksResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *ListChunksResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// GetChunkRequest represents a request to get a chunk.
// Follows AIP-131: https://google.aip.dev/131
type GetChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the chunk to retrieve.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}/chunks/{chunk}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional chunk type filter. If specified, returns a chunk of this type
	// from the same file. If not specified, returns the chunk identified by name.
	ChunkType     *Chunk_Type `protobuf:"varint,2,opt,name=chunk_type,json=chunkType,proto3,enum=artifact.v1alpha.Chunk_Type,oneof" json:"chunk_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetChunkRequest) GetChunkType() Chunk_Type {
	if x != nil && x.ChunkType != nil {
		return *x.ChunkType
	}
	return Chunk_TYPE_UNSPECIFIED
}

// GetChunkResponse represents a response for getting a chunk.
type GetChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chunk metadata, including markdown_reference for extracting content.
	// Clients should use GetFile to fetch the full content/summary markdown,
	// then use markdown_reference coordinates to extract the specific chunk text.
	Chunk         *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *GetChunkResponse) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// UpdateChunkRequest represents a request to update a chunk.
// Follows AIP-134: https://google.aip.dev/134
type UpdateChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the chunk to update.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}/chunks/{chunk}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// whether the chunk is retrievable
	Retrievable   bool `protobuf:"varint,2,opt,name=retrievable,proto3" json:"retrievable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunkRequest) Reset() {
	*x = UpdateChunkRequest{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkRequest) ProtoMessage() {}

func (x *UpdateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkRequest.ProtoReflect.Descriptor instead.
func (*UpdateChunkRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateChunkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChunkRequest) GetRetrievable() bool {
	if x != nil {
		return x.Retrievable
	}
	return false
}

// UpdateChunkResponse represents a response for updating a chunk.
type UpdateChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk
	Chunk         *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunkResponse) Reset() {
	*x = UpdateChunkResponse{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkResponse) ProtoMessage() {}

func (x *UpdateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkResponse.ProtoReflect.Descriptor instead.
func (*UpdateChunkResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChunkResponse) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// SearchChunksRequest represents a request to search for similar chunks.
type SearchChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name (namespace).
	// Format: `namespaces/{namespace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The knowledge base resource name to filter by (optional).
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`
	KnowledgeBase string `protobuf:"bytes,2,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	// Text prompt to look for similarities.
	TextPrompt string `protobuf:"bytes,3,opt,name=text_prompt,json=textPrompt,proto3" json:"text_prompt,omitempty"`
	// Top K. Default value: 5.
	TopK uint32 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Chunk type.
	Type Chunk_Type `protobuf:"varint,6,opt,name=type,proto3,enum=artifact.v1alpha.Chunk_Type" json:"type,omitempty"`
	// File media type.
	FileMediaType File_FileMediaType `protobuf:"varint,7,opt,name=file_media_type,json=fileMediaType,proto3,enum=artifact.v1alpha.File_FileMediaType" json:"file_media_type,omitempty"`
	// File resource names to filter by. When this field is provided, the response
	// will return only chunks that belong to the specified files.
	// Format:
	// `namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}`
	Files []string `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	// Tags to filter by. When multiple tags are provided, OR logic is applied.
	// Note: File filter takes precedence over tags, as tags apply to files.
	Tags          []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChunksRequest) Reset() {
	*x = SearchChunksRequest{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChunksRequest) ProtoMessage() {}

func (x *SearchChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChunksRequest.ProtoReflect.Descriptor instead.
func (*SearchChunksRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *SearchChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *SearchChunksRequest) GetKnowledgeBase() string {
	if x != nil {
		return x.KnowledgeBase
	}
	return ""
}

func (x *SearchChunksRequest) GetTextPrompt() string {
	if x != nil {
		return x.TextPrompt
	}
	return ""
}

func (x *SearchChunksRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchChunksRequest) GetType() Chunk_Type {
	if x != nil {
		return x.Type
	}
	return Chunk_TYPE_UNSPECIFIED
}

func (x *SearchChunksRequest) GetFileMediaType() File_FileMediaType {
	if x != nil {
		return x.FileMediaType
	}
	return File_FILE_MEDIA_TYPE_UNSPECIFIED
}

func (x *SearchChunksRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchChunksRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SearchChunksResponse represents a response for searching similar chunks.
type SearchChunksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunks
	SimilarChunks []*SimilarityChunk `protobuf:"bytes,1,rep,name=similar_chunks,json=similarChunks,proto3" json:"similar_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChunksResponse) Reset() {
	*x = SearchChunksResponse{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChunksResponse) ProtoMessage() {}

func (x *SearchChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChunksResponse.ProtoReflect.Descriptor instead.
func (*SearchChunksResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *SearchChunksResponse) GetSimilarChunks() []*SimilarityChunk {
	if x != nil {
		return x.SimilarChunks
	}
	return nil
}

// SimilarityChunk represents a chunk with similarity score.
type SimilarityChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk resource name.
	// Full resource name:
	// namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}/chunks/{chunk}
	Chunk string `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Similarity score.
	SimilarityScore float32 `protobuf:"fixed32,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	// Content.
	TextContent string `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// Source file resource name.
	// Full resource name:
	// namespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}
	File string `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	// Chunk metadata.
	ChunkMetadata *Chunk `protobuf:"bytes,5,opt,name=chunk_metadata,json=chunkMetadata,proto3" json:"chunk_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityChunk) Reset() {
	*x = SimilarityChunk{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityChunk) ProtoMessage() {}

func (x *SimilarityChunk) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityChunk.ProtoReflect.Descriptor instead.
func (*SimilarityChunk) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *SimilarityChunk) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *SimilarityChunk) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *SimilarityChunk) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *SimilarityChunk) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SimilarityChunk) GetChunkMetadata() *Chunk {
	if x != nil {
		return x.ChunkMetadata
	}
	return nil
}

// Reference represents the position of a chunk within a file.
type Chunk_Reference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start position of the chunk within the file.
	Start *File_Position `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// End position of the chunk within the file.
	End           *File_Position `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk_Reference) Reset() {
	*x = Chunk_Reference{}
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk_Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk_Reference) ProtoMessage() {}

func (x *Chunk_Reference) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_chunk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk_Reference.ProtoReflect.Descriptor instead.
func (*Chunk_Reference) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_chunk_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Chunk_Reference) GetStart() *File_Position {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Chunk_Reference) GetEnd() *File_Position {
	if x != nil {
		return x.End
	}
	return nil
}

var File_artifact_v1alpha_chunk_proto protoreflect.FileDescriptor

const file_artifact_v1alpha_chunk_proto_rawDesc = "" +
	"\n" +
	"\x1cartifact/v1alpha/chunk.proto\x12\x10artifact.v1alpha\x1a\x1bartifact/v1alpha/file.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x06\n" +
	"\x05Chunk\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x03R\x02id\x12%\n" +
	"\vretrievable\x18\x03 \x01(\bB\x03\xe0A\x03R\vretrievable\x12\x1b\n" +
	"\x06tokens\x18\x04 \x01(\rB\x03\xe0A\x03R\x06tokens\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12B\n" +
	"\roriginal_file\x18\x06 \x01(\tB\x1d\xe0A\x03\xfaA\x17\n" +
	"\x15api.instill.tech/FileR\foriginalFile\x125\n" +
	"\x04type\x18\a \x01(\x0e2\x1c.artifact.v1alpha.Chunk.TypeB\x03\xe0A\x03R\x04type\x12D\n" +
	"\treference\x18\b \x01(\v2!.artifact.v1alpha.Chunk.ReferenceB\x03\xe0A\x03R\treference\x12U\n" +
	"\x12markdown_reference\x18\t \x01(\v2!.artifact.v1alpha.Chunk.ReferenceB\x03\xe0A\x03R\x11markdownReference\x1a\x7f\n" +
	"\tReference\x12:\n" +
	"\x05start\x18\x01 \x01(\v2\x1f.artifact.v1alpha.File.PositionB\x03\xe0A\x03R\x05start\x126\n" +
	"\x03end\x18\x02 \x01(\v2\x1f.artifact.v1alpha.File.PositionB\x03\xe0A\x03R\x03end\"T\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTYPE_CONTENT\x10\x01\x12\x10\n" +
	"\fTYPE_SUMMARY\x10\x02\x12\x12\n" +
	"\x0eTYPE_AUGMENTED\x10\x03:X\xeaAU\x12Snamespaces/{namespace}/knowledge-bases/{knowledge_base}/files/{file}/chunks/{chunk}\"\xca\x01\n" +
	"\x11ListChunksRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12%\n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01H\x00R\bpageSize\x88\x01\x01\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01H\x01R\tpageToken\x88\x01\x01\x12 \n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01H\x02R\x06filter\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\t\n" +
	"\a_filter\"J\n" +
	"\x12ListChunksResponse\x124\n" +
	"\x06chunks\x18\x01 \x03(\v2\x17.artifact.v1alpha.ChunkB\x03\xe0A\x03R\x06chunks\"\x80\x01\n" +
	"\x0fGetChunkRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12E\n" +
	"\n" +
	"chunk_type\x18\x02 \x01(\x0e2\x1c.artifact.v1alpha.Chunk.TypeB\x03\xe0A\x01H\x00R\tchunkType\x88\x01\x01B\r\n" +
	"\v_chunk_type\"F\n" +
	"\x10GetChunkResponse\x122\n" +
	"\x05chunk\x18\x01 \x01(\v2\x17.artifact.v1alpha.ChunkB\x03\xe0A\x03R\x05chunk\"T\n" +
	"\x12UpdateChunkRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vretrievable\x18\x02 \x01(\bB\x03\xe0A\x02R\vretrievable\"I\n" +
	"\x13UpdateChunkResponse\x122\n" +
	"\x05chunk\x18\x01 \x01(\v2\x17.artifact.v1alpha.ChunkB\x03\xe0A\x03R\x05chunk\"\xa5\x03\n" +
	"\x13SearchChunksRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12M\n" +
	"\x0eknowledge_base\x18\x02 \x01(\tB&\xe0A\x01\xfaA \n" +
	"\x1eapi.instill.tech/KnowledgeBaseR\rknowledgeBase\x12$\n" +
	"\vtext_prompt\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"textPrompt\x12\x18\n" +
	"\x05top_k\x18\x04 \x01(\rB\x03\xe0A\x01R\x04topK\x125\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1c.artifact.v1alpha.Chunk.TypeB\x03\xe0A\x01R\x04type\x12Q\n" +
	"\x0ffile_media_type\x18\a \x01(\x0e2$.artifact.v1alpha.File.FileMediaTypeB\x03\xe0A\x01R\rfileMediaType\x123\n" +
	"\x05files\x18\t \x03(\tB\x1d\xe0A\x01\xfaA\x17\n" +
	"\x15api.instill.tech/FileR\x05files\x12\x17\n" +
	"\x04tags\x18\n" +
	" \x03(\tB\x03\xe0A\x01R\x04tagsJ\x04\b\x05\x10\x06J\x04\b\b\x10\t\"e\n" +
	"\x14SearchChunksResponse\x12M\n" +
	"\x0esimilar_chunks\x18\x01 \x03(\v2!.artifact.v1alpha.SimilarityChunkB\x03\xe0A\x03R\rsimilarChunks\"\x97\x02\n" +
	"\x0fSimilarityChunk\x124\n" +
	"\x05chunk\x18\x01 \x01(\tB\x1e\xe0A\x03\xfaA\x18\n" +
	"\x16api.instill.tech/ChunkR\x05chunk\x12.\n" +
	"\x10similarity_score\x18\x02 \x01(\x02B\x03\xe0A\x03R\x0fsimilarityScore\x12&\n" +
	"\ftext_content\x18\x03 \x01(\tB\x03\xe0A\x03R\vtextContent\x121\n" +
	"\x04file\x18\x04 \x01(\tB\x1d\xe0A\x03\xfaA\x17\n" +
	"\x15api.instill.tech/FileR\x04file\x12C\n" +
	"\x0echunk_metadata\x18\x05 \x01(\v2\x17.artifact.v1alpha.ChunkB\x03\xe0A\x03R\rchunkMetadataB\xc7\x01\n" +
	"\x14com.artifact.v1alphaB\n" +
	"ChunkProtoP\x01ZBgithub.com/instill-ai/protogen-go/artifact/v1alpha;artifactv1alpha\xa2\x02\x03AXX\xaa\x02\x10Artifact.V1alpha\xca\x02\x10Artifact\\V1alpha\xe2\x02\x1cArtifact\\V1alpha\\GPBMetadata\xea\x02\x11Artifact::V1alphab\x06proto3"

var (
	file_artifact_v1alpha_chunk_proto_rawDescOnce sync.Once
	file_artifact_v1alpha_chunk_proto_rawDescData []byte
)

func file_artifact_v1alpha_chunk_proto_rawDescGZIP() []byte {
	file_artifact_v1alpha_chunk_proto_rawDescOnce.Do(func() {
		file_artifact_v1alpha_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v1alpha_chunk_proto_rawDesc), len(file_artifact_v1alpha_chunk_proto_rawDesc)))
	})
	return file_artifact_v1alpha_chunk_proto_rawDescData
}

var file_artifact_v1alpha_chunk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_v1alpha_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_artifact_v1alpha_chunk_proto_goTypes = []any{
	(Chunk_Type)(0),               // 0: artifact.v1alpha.Chunk.Type
	(*Chunk)(nil),                 // 1: artifact.v1alpha.Chunk
	(*ListChunksRequest)(nil),     // 2: artifact.v1alpha.ListChunksRequest
	(*ListChunksResponse)(nil),    // 3: artifact.v1alpha.ListChunksResponse
	(*GetChunkRequest)(nil),       // 4: artifact.v1alpha.GetChunkRequest
	(*GetChunkResponse)(nil),      // 5: artifact.v1alpha.GetChunkResponse
	(*UpdateChunkRequest)(nil),    // 6: artifact.v1alpha.UpdateChunkRequest
	(*UpdateChunkResponse)(nil),   // 7: artifact.v1alpha.UpdateChunkResponse
	(*SearchChunksRequest)(nil),   // 8: artifact.v1alpha.SearchChunksRequest
	(*SearchChunksResponse)(nil),  // 9: artifact.v1alpha.SearchChunksResponse
	(*SimilarityChunk)(nil),       // 10: artifact.v1alpha.SimilarityChunk
	(*Chunk_Reference)(nil),       // 11: artifact.v1alpha.Chunk.Reference
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(File_FileMediaType)(0),       // 13: artifact.v1alpha.File.FileMediaType
	(*File_Position)(nil),         // 14: artifact.v1alpha.File.Position
}
var file_artifact_v1alpha_chunk_proto_depIdxs = []int32{
	12, // 0: artifact.v1alpha.Chunk.create_time:type_name -> google.protobuf.Timestamp
	0,  // 1: artifact.v1alpha.Chunk.type:type_name -> artifact.v1alpha.Chunk.Type
	11, // 2: artifact.v1alpha.Chunk.reference:type_name -> artifact.v1alpha.Chunk.Reference
	11, // 3: artifact.v1alpha.Chunk.markdown_reference:type_name -> artifact.v1alpha.Chunk.Reference
	1,  // 4: artifact.v1alpha.ListChunksResponse.chunks:type_name -> artifact.v1alpha.Chunk
	0,  // 5: artifact.v1alpha.GetChunkRequest.chunk_type:type_name -> artifact.v1alpha.Chunk.Type
	1,  // 6: artifact.v1alpha.GetChunkResponse.chunk:type_name -> artifact.v1alpha.Chunk
	1,  // 7: artifact.v1alpha.UpdateChunkResponse.chunk:type_name -> artifact.v1alpha.Chunk
	0,  // 8: artifact.v1alpha.SearchChunksRequest.type:type_name -> artifact.v1alpha.Chunk.Type
	13, // 9: artifact.v1alpha.SearchChunksRequest.file_media_type:type_name -> artifact.v1alpha.File.FileMediaType
	10, // 10: artifact.v1alpha.SearchChunksResponse.similar_chunks:type_name -> artifact.v1alpha.SimilarityChunk
	1,  // 11: artifact.v1alpha.SimilarityChunk.chunk_metadata:type_name -> artifact.v1alpha.Chunk
	14, // 12: artifact.v1alpha.Chunk.Reference.start:type_name -> artifact.v1alpha.File.Position
	14, // 13: artifact.v1alpha.Chunk.Reference.end:type_name -> artifact.v1alpha.File.Position
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_artifact_v1alpha_chunk_proto_init() }
func file_artifact_v1alpha_chunk_proto_init() {
	if File_artifact_v1alpha_chunk_proto != nil {
		return
	}
	file_artifact_v1alpha_file_proto_init()
	file_artifact_v1alpha_chunk_proto_msgTypes[1].OneofWrappers = []any{}
	file_artifact_v1alpha_chunk_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v1alpha_chunk_proto_rawDesc), len(file_artifact_v1alpha_chunk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_v1alpha_chunk_proto_goTypes,
		DependencyIndexes: file_artifact_v1alpha_chunk_proto_depIdxs,
		EnumInfos:         file_artifact_v1alpha_chunk_proto_enumTypes,
		MessageInfos:      file_artifact_v1alpha_chunk_proto_msgTypes,
	}.Build()
	File_artifact_v1alpha_chunk_proto = out.File
	file_artifact_v1alpha_chunk_proto_goTypes = nil
	file_artifact_v1alpha_chunk_proto_depIdxs = nil
}
