// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: artifact/v1alpha/knowledge_base.proto

package artifactv1alpha

import (
	v1beta "github.com/instill-ai/protogen-go/mgmt/v1beta"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Knowledge Base Type. e.g. "persistent" or "ephemeral"
type KnowledgeBaseType int32

const (
	// UNSPECIFIED
	KnowledgeBaseType_KNOWLEDGE_BASE_TYPE_UNSPECIFIED KnowledgeBaseType = 0
	// PERSISTENT
	KnowledgeBaseType_KNOWLEDGE_BASE_TYPE_PERSISTENT KnowledgeBaseType = 1
	// EPHEMERAL
	KnowledgeBaseType_KNOWLEDGE_BASE_TYPE_EPHEMERAL KnowledgeBaseType = 2
)

// Enum value maps for KnowledgeBaseType.
var (
	KnowledgeBaseType_name = map[int32]string{
		0: "KNOWLEDGE_BASE_TYPE_UNSPECIFIED",
		1: "KNOWLEDGE_BASE_TYPE_PERSISTENT",
		2: "KNOWLEDGE_BASE_TYPE_EPHEMERAL",
	}
	KnowledgeBaseType_value = map[string]int32{
		"KNOWLEDGE_BASE_TYPE_UNSPECIFIED": 0,
		"KNOWLEDGE_BASE_TYPE_PERSISTENT":  1,
		"KNOWLEDGE_BASE_TYPE_EPHEMERAL":   2,
	}
)

func (x KnowledgeBaseType) Enum() *KnowledgeBaseType {
	p := new(KnowledgeBaseType)
	*p = x
	return p
}

func (x KnowledgeBaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KnowledgeBaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_v1alpha_knowledge_base_proto_enumTypes[0].Descriptor()
}

func (KnowledgeBaseType) Type() protoreflect.EnumType {
	return &file_artifact_v1alpha_knowledge_base_proto_enumTypes[0]
}

func (x KnowledgeBaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KnowledgeBaseType.Descriptor instead.
func (KnowledgeBaseType) EnumDescriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{0}
}

// KnowledgeBase represents a knowledge base.
// Field ordering follows AIP standard: name(1), id(2), display_name(3),
// slug(4), aliases(5), description(6)
type KnowledgeBase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: Canonical resource name.
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Field 2: Immutable canonical resource ID (80-96 bits entropy, base62).
	// Example: "kb-8f3a2k9E7c1"
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Field 3: Human-readable display name for UI.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Field 4: URL-friendly slug (NO prefix).
	// If omitted, server generates from display_name.
	// If provided, server validates and persists it.
	// Slug is NOT part of resource identity.
	// Example: "my-knowledge-base"
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Field 5: Previous slugs for backward compatibility.
	// When display_name changes, a new slug is generated and old slugs are stored
	// here.
	Aliases []string `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// Field 6: Optional description.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Field 7: Creation time.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Field 8: Last update time.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The knowledge base tags.
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// The knowledge base type (persistent or ephemeral).
	// Default is PERSISTENT if not specified during creation.
	Type KnowledgeBaseType `protobuf:"varint,10,opt,name=type,proto3,enum=artifact.v1alpha.KnowledgeBaseType" json:"type,omitempty"`
	// System ID defines how the knowledge base will be created based on the
	// system's RAG configurations including:
	// - AI model family (e.g., "openai", "gemini")
	// - Embedding vector dimensionality
	// - Chunking method
	// - Other RAG-related settings
	//
	// Available systems: "openai", "gemini", or custom systems defined in the
	// system table. If not specified, defaults to the default system.
	SystemId *string `protobuf:"bytes,11,opt,name=system_id,json=systemId,proto3,oneof" json:"system_id,omitempty"`
	// The embedding configuration for the knowledge base.
	EmbeddingConfig *KnowledgeBase_EmbeddingConfig `protobuf:"bytes,12,opt,name=embedding_config,json=embeddingConfig,proto3" json:"embedding_config,omitempty"`
	// The ID of the active Milvus collection for this knowledge base.
	// This supports collection versioning for embedding dimension changes.
	ActiveCollectionId string `protobuf:"bytes,13,opt,name=active_collection_id,json=activeCollectionId,proto3" json:"active_collection_id,omitempty"`
	// Resource name of the owner namespace.
	// Example: "namespaces/usr-7k2m9p4w1n3" or "namespaces/org-3t8f5q2x6b1"
	OwnerName string `protobuf:"bytes,14,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	// Knowledge base owner (User or Organization).
	Owner *v1beta.Owner `protobuf:"bytes,15,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// Full resource name of the user who created this knowledge base.
	// Format: `users/{user}`
	// Optional for system-created knowledge bases (e.g., instill-agent).
	CreatorName *string `protobuf:"bytes,16,opt,name=creator_name,json=creatorName,proto3,oneof" json:"creator_name,omitempty"`
	// The user who created this knowledge base.
	// Populated when creator_name is present.
	Creator *v1beta.User `protobuf:"bytes,17,opt,name=creator,proto3,oneof" json:"creator,omitempty"`
	// The total files in knowledge base.
	TotalFiles uint32 `protobuf:"varint,18,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	// The total tokens in knowledge base.
	TotalTokens uint32 `protobuf:"varint,19,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// The current used storage in knowledge base.
	UsedStorage uint64 `protobuf:"varint,20,opt,name=used_storage,json=usedStorage,proto3" json:"used_storage,omitempty"`
	// The downstream apps.
	DownstreamApps []string `protobuf:"bytes,21,rep,name=downstream_apps,json=downstreamApps,proto3" json:"downstream_apps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeBase) Reset() {
	*x = KnowledgeBase{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBase) ProtoMessage() {}

func (x *KnowledgeBase) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBase.ProtoReflect.Descriptor instead.
func (*KnowledgeBase) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeBase) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *KnowledgeBase) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *KnowledgeBase) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *KnowledgeBase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBase) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *KnowledgeBase) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *KnowledgeBase) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowledgeBase) GetType() KnowledgeBaseType {
	if x != nil {
		return x.Type
	}
	return KnowledgeBaseType_KNOWLEDGE_BASE_TYPE_UNSPECIFIED
}

func (x *KnowledgeBase) GetSystemId() string {
	if x != nil && x.SystemId != nil {
		return *x.SystemId
	}
	return ""
}

func (x *KnowledgeBase) GetEmbeddingConfig() *KnowledgeBase_EmbeddingConfig {
	if x != nil {
		return x.EmbeddingConfig
	}
	return nil
}

func (x *KnowledgeBase) GetActiveCollectionId() string {
	if x != nil {
		return x.ActiveCollectionId
	}
	return ""
}

func (x *KnowledgeBase) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *KnowledgeBase) GetOwner() *v1beta.Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *KnowledgeBase) GetCreatorName() string {
	if x != nil && x.CreatorName != nil {
		return *x.CreatorName
	}
	return ""
}

func (x *KnowledgeBase) GetCreator() *v1beta.User {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *KnowledgeBase) GetTotalFiles() uint32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *KnowledgeBase) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *KnowledgeBase) GetUsedStorage() uint64 {
	if x != nil {
		return x.UsedStorage
	}
	return 0
}

func (x *KnowledgeBase) GetDownstreamApps() []string {
	if x != nil {
		return x.DownstreamApps
	}
	return nil
}

// CreateKnowledgeBaseRequest represents a request to create a knowledge base.
// Follows AIP-133: https://google.aip.dev/133
type CreateKnowledgeBaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name.
	// Format: `namespaces/{namespace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The knowledge base resource to create.
	// Required fields: display_name
	// Optional fields: id (auto-generated from display_name if not provided),
	//
	//	description, tags, type, system_id
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,2,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKnowledgeBaseRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// CreateKnowledgeBaseResponse represents a response for creating a knowledge
// base.
type CreateKnowledgeBaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseResponse) Reset() {
	*x = CreateKnowledgeBaseResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// GetKnowledgeBaseRequest represents a request to get a knowledge base.
// Follows AIP-131: https://google.aip.dev/131
type GetKnowledgeBaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the knowledge base to retrieve.
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeBaseRequest) Reset() {
	*x = GetKnowledgeBaseRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseRequest) ProtoMessage() {}

func (x *GetKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{3}
}

func (x *GetKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetKnowledgeBaseResponse represents a response for getting a knowledge base.
type GetKnowledgeBaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeBaseResponse) Reset() {
	*x = GetKnowledgeBaseResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseResponse) ProtoMessage() {}

func (x *GetKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{4}
}

func (x *GetKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// ListKnowledgeBasesRequest represents a request to list knowledge bases.
// Follows AIP-132: https://google.aip.dev/132
// Does not include ephemeral knowledge bases.
type ListKnowledgeBasesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name.
	// Format: `namespaces/{namespace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of knowledge bases to return. If this parameter is
	// unspecified, at most 10 knowledge bases will be returned. The cap value for
	// this parameter is 100 (i.e. any value above that will be coerced to 100).
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Page token for pagination.
	PageToken *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Filter can hold an [AIP-160](https://google.aip.dev/160)-compliant filter
	// expression.
	// - `id="<knowledge_base_id>"` or `uid="<uuid>"` - Filter by specific
	// knowledge base ID/UID
	// - `q="<text>"` - Fuzzy search on knowledge base ID and description
	//
	// **Examples**:
	// - Filter by ID: `id="my-knowledge-base"`
	// - Search knowledge bases: `q="my-knowledge-base"`
	Filter        *string `protobuf:"bytes,4,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesRequest) Reset() {
	*x = ListKnowledgeBasesRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesRequest) ProtoMessage() {}

func (x *ListKnowledgeBasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{5}
}

func (x *ListKnowledgeBasesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListKnowledgeBasesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListKnowledgeBasesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListKnowledgeBasesRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

// ListKnowledgeBasesResponse represents a response for listing knowledge bases.
type ListKnowledgeBasesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of knowledge bases.
	KnowledgeBases []*KnowledgeBase `protobuf:"bytes,1,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
	// Next page token for pagination.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total number of knowledge bases matching the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesResponse) Reset() {
	*x = ListKnowledgeBasesResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesResponse) ProtoMessage() {}

func (x *ListKnowledgeBasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{6}
}

func (x *ListKnowledgeBasesResponse) GetKnowledgeBases() []*KnowledgeBase {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

func (x *ListKnowledgeBasesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListKnowledgeBasesResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateKnowledgeBaseRequest represents a request to update a knowledge base.
// Follows AIP-134: https://google.aip.dev/134
type UpdateKnowledgeBaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The knowledge base resource to update. The knowledge base's `name` field
	// identifies the resource.
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	// The update mask specifies the subset of fields that should be modified.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseRequest) Reset() {
	*x = UpdateKnowledgeBaseRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseRequest) ProtoMessage() {}

func (x *UpdateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateKnowledgeBaseRequest) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

func (x *UpdateKnowledgeBaseRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateKnowledgeBaseResponse represents a response for updating a knowledge
// base.
type UpdateKnowledgeBaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseResponse) Reset() {
	*x = UpdateKnowledgeBaseResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseResponse) ProtoMessage() {}

func (x *UpdateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// DeleteKnowledgeBaseRequest represents a request to delete a knowledge base.
// Follows AIP-135: https://google.aip.dev/135
type DeleteKnowledgeBaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the knowledge base to delete.
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeBaseRequest) Reset() {
	*x = DeleteKnowledgeBaseRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseRequest) ProtoMessage() {}

func (x *DeleteKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteKnowledgeBaseResponse represents a response for deleting a knowledge
// base.
type DeleteKnowledgeBaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deleted knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeBaseResponse) Reset() {
	*x = DeleteKnowledgeBaseResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseResponse) ProtoMessage() {}

func (x *DeleteKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// CreateKnowledgeBaseAdminRequest represents a request to create a system-level
// knowledge base without a creator (admin only).
// Follows AIP-133: https://google.aip.dev/133
type CreateKnowledgeBaseAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource name.
	// Format: `namespaces/{namespace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The knowledge base resource to create.
	// Required fields: id (for admin, id is required rather than auto-generated)
	// Optional fields: display_name (defaults to id), description, tags, type
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,2,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseAdminRequest) Reset() {
	*x = CreateKnowledgeBaseAdminRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseAdminRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{11}
}

func (x *CreateKnowledgeBaseAdminRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateKnowledgeBaseAdminRequest) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// CreateKnowledgeBaseAdminResponse represents a response for creating a
// system-level knowledge base.
type CreateKnowledgeBaseAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseAdminResponse) Reset() {
	*x = CreateKnowledgeBaseAdminResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseAdminResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseAdminResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{12}
}

func (x *CreateKnowledgeBaseAdminResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// UpdateKnowledgeBaseAdminRequest represents a request to update a knowledge
// base with system-reserved tags (admin only).
// Follows AIP-134: https://google.aip.dev/134
type UpdateKnowledgeBaseAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The knowledge base resource to update. The knowledge base's `name` field
	// identifies the resource.
	// Format: `namespaces/{namespace}/knowledge-bases/{knowledge_base}`
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	// The update mask specifies the subset of fields that should be modified.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseAdminRequest) Reset() {
	*x = UpdateKnowledgeBaseAdminRequest{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseAdminRequest) ProtoMessage() {}

func (x *UpdateKnowledgeBaseAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseAdminRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateKnowledgeBaseAdminRequest) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

func (x *UpdateKnowledgeBaseAdminRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateKnowledgeBaseAdminResponse represents a response for updating a
// knowledge base.
type UpdateKnowledgeBaseAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated knowledge base resource.
	KnowledgeBase *KnowledgeBase `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseAdminResponse) Reset() {
	*x = UpdateKnowledgeBaseAdminResponse{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseAdminResponse) ProtoMessage() {}

func (x *UpdateKnowledgeBaseAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseAdminResponse.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseAdminResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateKnowledgeBaseAdminResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// EmbeddingConfig defines the embedding configuration for a knowledge base
type KnowledgeBase_EmbeddingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The AI model family used for embeddings (e.g., "gemini", "openai")
	ModelFamily string `protobuf:"bytes,1,opt,name=model_family,json=modelFamily,proto3" json:"model_family,omitempty"`
	// The dimensionality of the embedding vectors
	Dimensionality uint32 `protobuf:"varint,2,opt,name=dimensionality,proto3" json:"dimensionality,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeBase_EmbeddingConfig) Reset() {
	*x = KnowledgeBase_EmbeddingConfig{}
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBase_EmbeddingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBase_EmbeddingConfig) ProtoMessage() {}

func (x *KnowledgeBase_EmbeddingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1alpha_knowledge_base_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBase_EmbeddingConfig.ProtoReflect.Descriptor instead.
func (*KnowledgeBase_EmbeddingConfig) Descriptor() ([]byte, []int) {
	return file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP(), []int{0, 0}
}

func (x *KnowledgeBase_EmbeddingConfig) GetModelFamily() string {
	if x != nil {
		return x.ModelFamily
	}
	return ""
}

func (x *KnowledgeBase_EmbeddingConfig) GetDimensionality() uint32 {
	if x != nil {
		return x.Dimensionality
	}
	return 0
}

var File_artifact_v1alpha_knowledge_base_proto protoreflect.FileDescriptor

const file_artifact_v1alpha_knowledge_base_proto_rawDesc = "" +
	"\n" +
	"%artifact/v1alpha/knowledge_base.proto\x12\x10artifact.v1alpha\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16mgmt/v1beta/mgmt.proto\"\xaf\t\n" +
	"\rKnowledgeBase\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x03R\x02id\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\x03\xe0A\x02R\vdisplayName\x12\x17\n" +
	"\x04slug\x18\x04 \x01(\tB\x03\xe0A\x01R\x04slug\x12\x1d\n" +
	"\aaliases\x18\x05 \x03(\tB\x03\xe0A\x03R\aaliases\x12%\n" +
	"\vdescription\x18\x06 \x01(\tB\x03\xe0A\x01R\vdescription\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\x17\n" +
	"\x04tags\x18\t \x03(\tB\x03\xe0A\x01R\x04tags\x12<\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2#.artifact.v1alpha.KnowledgeBaseTypeB\x03\xe0A\x01R\x04type\x12%\n" +
	"\tsystem_id\x18\v \x01(\tB\x03\xe0A\x01H\x00R\bsystemId\x88\x01\x01\x12_\n" +
	"\x10embedding_config\x18\f \x01(\v2/.artifact.v1alpha.KnowledgeBase.EmbeddingConfigB\x03\xe0A\x01R\x0fembeddingConfig\x125\n" +
	"\x14active_collection_id\x18\r \x01(\tB\x03\xe0A\x03R\x12activeCollectionId\x12\"\n" +
	"\n" +
	"owner_name\x18\x0e \x01(\tB\x03\xe0A\x03R\townerName\x122\n" +
	"\x05owner\x18\x0f \x01(\v2\x12.mgmt.v1beta.OwnerB\x03\xe0A\x03H\x01R\x05owner\x88\x01\x01\x12+\n" +
	"\fcreator_name\x18\x10 \x01(\tB\x03\xe0A\x03H\x02R\vcreatorName\x88\x01\x01\x125\n" +
	"\acreator\x18\x11 \x01(\v2\x11.mgmt.v1beta.UserB\x03\xe0A\x03H\x03R\acreator\x88\x01\x01\x12$\n" +
	"\vtotal_files\x18\x12 \x01(\rB\x03\xe0A\x03R\n" +
	"totalFiles\x12&\n" +
	"\ftotal_tokens\x18\x13 \x01(\rB\x03\xe0A\x03R\vtotalTokens\x12&\n" +
	"\fused_storage\x18\x14 \x01(\x04B\x03\xe0A\x03R\vusedStorage\x12,\n" +
	"\x0fdownstream_apps\x18\x15 \x03(\tB\x03\xe0A\x03R\x0edownstreamApps\x1a\\\n" +
	"\x0fEmbeddingConfig\x12!\n" +
	"\fmodel_family\x18\x01 \x01(\tR\vmodelFamily\x12&\n" +
	"\x0edimensionality\x18\x02 \x01(\rR\x0edimensionality:\\\xeaAY\n" +
	"\x1eapi.instill.tech/KnowledgeBase\x127namespaces/{namespace}/knowledge-bases/{knowledge_base}B\f\n" +
	"\n" +
	"_system_idB\b\n" +
	"\x06_ownerB\x0f\n" +
	"\r_creator_nameB\n" +
	"\n" +
	"\b_creator\"\x86\x01\n" +
	"\x1aCreateKnowledgeBaseRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12K\n" +
	"\x0eknowledge_base\x18\x02 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x02R\rknowledgeBase\"j\n" +
	"\x1bCreateKnowledgeBaseResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase\"U\n" +
	"\x17GetKnowledgeBaseRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n" +
	"\x1eapi.instill.tech/KnowledgeBaseR\x04name\"g\n" +
	"\x18GetKnowledgeBaseResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase\"\xd2\x01\n" +
	"\x19ListKnowledgeBasesRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12%\n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01H\x00R\bpageSize\x88\x01\x01\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01H\x01R\tpageToken\x88\x01\x01\x12 \n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01H\x02R\x06filter\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\t\n" +
	"\a_filter\"\xbc\x01\n" +
	"\x1aListKnowledgeBasesResponse\x12M\n" +
	"\x0fknowledge_bases\x18\x01 \x03(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\x0eknowledgeBases\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x03\xe0A\x03R\rnextPageToken\x12\"\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05B\x03\xe0A\x03R\ttotalSize\"\xab\x01\n" +
	"\x1aUpdateKnowledgeBaseRequest\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x02R\rknowledgeBase\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"j\n" +
	"\x1bUpdateKnowledgeBaseResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase\"X\n" +
	"\x1aDeleteKnowledgeBaseRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n" +
	"\x1eapi.instill.tech/KnowledgeBaseR\x04name\"j\n" +
	"\x1bDeleteKnowledgeBaseResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase\"\x8b\x01\n" +
	"\x1fCreateKnowledgeBaseAdminRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12K\n" +
	"\x0eknowledge_base\x18\x02 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x02R\rknowledgeBase\"o\n" +
	" CreateKnowledgeBaseAdminResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase\"\xb0\x01\n" +
	"\x1fUpdateKnowledgeBaseAdminRequest\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x02R\rknowledgeBase\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"o\n" +
	" UpdateKnowledgeBaseAdminResponse\x12K\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1f.artifact.v1alpha.KnowledgeBaseB\x03\xe0A\x03R\rknowledgeBase*\x7f\n" +
	"\x11KnowledgeBaseType\x12#\n" +
	"\x1fKNOWLEDGE_BASE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eKNOWLEDGE_BASE_TYPE_PERSISTENT\x10\x01\x12!\n" +
	"\x1dKNOWLEDGE_BASE_TYPE_EPHEMERAL\x10\x02B\xcf\x01\n" +
	"\x14com.artifact.v1alphaB\x12KnowledgeBaseProtoP\x01ZBgithub.com/instill-ai/protogen-go/artifact/v1alpha;artifactv1alpha\xa2\x02\x03AXX\xaa\x02\x10Artifact.V1alpha\xca\x02\x10Artifact\\V1alpha\xe2\x02\x1cArtifact\\V1alpha\\GPBMetadata\xea\x02\x11Artifact::V1alphab\x06proto3"

var (
	file_artifact_v1alpha_knowledge_base_proto_rawDescOnce sync.Once
	file_artifact_v1alpha_knowledge_base_proto_rawDescData []byte
)

func file_artifact_v1alpha_knowledge_base_proto_rawDescGZIP() []byte {
	file_artifact_v1alpha_knowledge_base_proto_rawDescOnce.Do(func() {
		file_artifact_v1alpha_knowledge_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v1alpha_knowledge_base_proto_rawDesc), len(file_artifact_v1alpha_knowledge_base_proto_rawDesc)))
	})
	return file_artifact_v1alpha_knowledge_base_proto_rawDescData
}

var file_artifact_v1alpha_knowledge_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_v1alpha_knowledge_base_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_artifact_v1alpha_knowledge_base_proto_goTypes = []any{
	(KnowledgeBaseType)(0),                   // 0: artifact.v1alpha.KnowledgeBaseType
	(*KnowledgeBase)(nil),                    // 1: artifact.v1alpha.KnowledgeBase
	(*CreateKnowledgeBaseRequest)(nil),       // 2: artifact.v1alpha.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseResponse)(nil),      // 3: artifact.v1alpha.CreateKnowledgeBaseResponse
	(*GetKnowledgeBaseRequest)(nil),          // 4: artifact.v1alpha.GetKnowledgeBaseRequest
	(*GetKnowledgeBaseResponse)(nil),         // 5: artifact.v1alpha.GetKnowledgeBaseResponse
	(*ListKnowledgeBasesRequest)(nil),        // 6: artifact.v1alpha.ListKnowledgeBasesRequest
	(*ListKnowledgeBasesResponse)(nil),       // 7: artifact.v1alpha.ListKnowledgeBasesResponse
	(*UpdateKnowledgeBaseRequest)(nil),       // 8: artifact.v1alpha.UpdateKnowledgeBaseRequest
	(*UpdateKnowledgeBaseResponse)(nil),      // 9: artifact.v1alpha.UpdateKnowledgeBaseResponse
	(*DeleteKnowledgeBaseRequest)(nil),       // 10: artifact.v1alpha.DeleteKnowledgeBaseRequest
	(*DeleteKnowledgeBaseResponse)(nil),      // 11: artifact.v1alpha.DeleteKnowledgeBaseResponse
	(*CreateKnowledgeBaseAdminRequest)(nil),  // 12: artifact.v1alpha.CreateKnowledgeBaseAdminRequest
	(*CreateKnowledgeBaseAdminResponse)(nil), // 13: artifact.v1alpha.CreateKnowledgeBaseAdminResponse
	(*UpdateKnowledgeBaseAdminRequest)(nil),  // 14: artifact.v1alpha.UpdateKnowledgeBaseAdminRequest
	(*UpdateKnowledgeBaseAdminResponse)(nil), // 15: artifact.v1alpha.UpdateKnowledgeBaseAdminResponse
	(*KnowledgeBase_EmbeddingConfig)(nil),    // 16: artifact.v1alpha.KnowledgeBase.EmbeddingConfig
	(*timestamppb.Timestamp)(nil),            // 17: google.protobuf.Timestamp
	(*v1beta.Owner)(nil),                     // 18: mgmt.v1beta.Owner
	(*v1beta.User)(nil),                      // 19: mgmt.v1beta.User
	(*fieldmaskpb.FieldMask)(nil),            // 20: google.protobuf.FieldMask
}
var file_artifact_v1alpha_knowledge_base_proto_depIdxs = []int32{
	17, // 0: artifact.v1alpha.KnowledgeBase.create_time:type_name -> google.protobuf.Timestamp
	17, // 1: artifact.v1alpha.KnowledgeBase.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: artifact.v1alpha.KnowledgeBase.type:type_name -> artifact.v1alpha.KnowledgeBaseType
	16, // 3: artifact.v1alpha.KnowledgeBase.embedding_config:type_name -> artifact.v1alpha.KnowledgeBase.EmbeddingConfig
	18, // 4: artifact.v1alpha.KnowledgeBase.owner:type_name -> mgmt.v1beta.Owner
	19, // 5: artifact.v1alpha.KnowledgeBase.creator:type_name -> mgmt.v1beta.User
	1,  // 6: artifact.v1alpha.CreateKnowledgeBaseRequest.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 7: artifact.v1alpha.CreateKnowledgeBaseResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 8: artifact.v1alpha.GetKnowledgeBaseResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 9: artifact.v1alpha.ListKnowledgeBasesResponse.knowledge_bases:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 10: artifact.v1alpha.UpdateKnowledgeBaseRequest.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	20, // 11: artifact.v1alpha.UpdateKnowledgeBaseRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 12: artifact.v1alpha.UpdateKnowledgeBaseResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 13: artifact.v1alpha.DeleteKnowledgeBaseResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 14: artifact.v1alpha.CreateKnowledgeBaseAdminRequest.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 15: artifact.v1alpha.CreateKnowledgeBaseAdminResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	1,  // 16: artifact.v1alpha.UpdateKnowledgeBaseAdminRequest.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	20, // 17: artifact.v1alpha.UpdateKnowledgeBaseAdminRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 18: artifact.v1alpha.UpdateKnowledgeBaseAdminResponse.knowledge_base:type_name -> artifact.v1alpha.KnowledgeBase
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_artifact_v1alpha_knowledge_base_proto_init() }
func file_artifact_v1alpha_knowledge_base_proto_init() {
	if File_artifact_v1alpha_knowledge_base_proto != nil {
		return
	}
	file_artifact_v1alpha_knowledge_base_proto_msgTypes[0].OneofWrappers = []any{}
	file_artifact_v1alpha_knowledge_base_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v1alpha_knowledge_base_proto_rawDesc), len(file_artifact_v1alpha_knowledge_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_v1alpha_knowledge_base_proto_goTypes,
		DependencyIndexes: file_artifact_v1alpha_knowledge_base_proto_depIdxs,
		EnumInfos:         file_artifact_v1alpha_knowledge_base_proto_enumTypes,
		MessageInfos:      file_artifact_v1alpha_knowledge_base_proto_msgTypes,
	}.Build()
	File_artifact_v1alpha_knowledge_base_proto = out.File
	file_artifact_v1alpha_knowledge_base_proto_goTypes = nil
	file_artifact_v1alpha_knowledge_base_proto_depIdxs = nil
}
